// <auto-generated />
using System;
using Allport_s_League_Scrambler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Allport_s_League_Scrambler.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Allport_s_League_Scrambler.Models.KingQueenPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KingQueenTeamId");

                    b.Property<int>("PlayerId");

                    b.HasKey("Id");

                    b.HasIndex("KingQueenTeamId");

                    b.HasIndex("PlayerId");

                    b.ToTable("KingQueenPlayer");
                });

            modelBuilder.Entity("Allport_s_League_Scrambler.Models.KingQueenTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfTeam");

                    b.Property<int>("LeagueID");

                    b.Property<int>("ScrambleNumber");

                    b.HasKey("Id");

                    b.ToTable("KingQueenTeam");
                });

            modelBuilder.Entity("Allport_s_League_Scrambler.Models.LeagueTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LeagueID");

                    b.Property<string>("TeamName");

                    b.Property<int>("TotalLosses");

                    b.Property<int>("TotalWins");

                    b.HasKey("Id");

                    b.ToTable("LeagueTeam");
                });

            modelBuilder.Entity("Allport_s_League_Scrambler.Models.LeagueType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LeagueName");

                    b.HasKey("ID");

                    b.ToTable("LeagueType");
                });

            modelBuilder.Entity("Allport_s_League_Scrambler.Models.Password", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("password");

                    b.HasKey("Id");

                    b.ToTable("Password");
                });

            modelBuilder.Entity("Allport_s_League_Scrambler.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<bool>("IsMale");

                    b.Property<bool?>("IsSub");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Allport_s_League_Scrambler.Models.PlayerScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("PlayersLeagueID");

                    b.Property<int>("PlayersScore");

                    b.HasKey("Id");

                    b.ToTable("PlayerScore");
                });

            modelBuilder.Entity("Allport_s_League_Scrambler.Models.PlayersLeague", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsSub");

                    b.Property<int>("LeagueID");

                    b.Property<int>("PlayerID");

                    b.HasKey("Id");

                    b.ToTable("PlayersLeague");
                });

            modelBuilder.Entity("Allport_s_League_Scrambler.Models.TeamScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("Team1ID");

                    b.Property<int>("Team1Score");

                    b.Property<int>("Team2ID");

                    b.Property<int>("Team2Score");

                    b.HasKey("Id");

                    b.ToTable("TeamScore");
                });

            modelBuilder.Entity("Allport_s_League_Scrambler.Models.KingQueenPlayer", b =>
                {
                    b.HasOne("Allport_s_League_Scrambler.Models.KingQueenTeam", "KingQueenTeam")
                        .WithMany("KingQueenPlayers")
                        .HasForeignKey("KingQueenTeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Allport_s_League_Scrambler.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
